//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTaiSan_UserManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceSparePart
    {
        public int Id { get; set; }
        public string SparePartName { get; set; }
        public string SparePartCode { get; set; }
        public Nullable<int> DeviceType { get; set; }
        public Nullable<int> TotalSparePart { get; set; }
        public Nullable<int> RemainingAmount { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string Notes { get; set; }
        public string Config { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<int> Isdelete { get; set; }
    }
}
